apiVersion: apps/v1
kind: Deployment
metadata:
  name: rr2mqtt
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rr2mqtt
  template:
    metadata:
      labels:
        app: rr2mqtt
    spec:
      containers:
        - name: rr2mqtt
          image: localhost:32000/roborock_mqtt_bridge8:arm
          imagePullPolicy: IfNotPresent
          env:
              - name: RR_EMAIL
                value: "sprekendeklok@gmail.com"
              - name: RR_PASSWORD
                value: "zihzuv-4wifpy-nYpguf"
              - name: RR_DEVICE_ID
                value: "7X5ZCIiHsvrzbBdl65Whly"
              - name: MQTT_BROKER
                value: "192.168.1.101"
              - name: MQTT_PORT
                value: "1883"
              - name: MQTT_TOPIC_PREFIX
                value: "living/robot_vacuum"
              - name: MQTT_USER
                value: "rr2mqtt"
              - name: MQTT_PASSWORD
                value: "Ropjur-qurhev-fazsi7"
              - name: POLLING_INTERVAL
                value: "60"
              - name: DEVICE_UPDATE_INTERVAL
                value: "86400"
              - name: PUSH_TO_HOMEASSISTANT
                value: "True"
              - name: LOGIN_DATA_PATH
                value: "/data/login.json"
          livenessProbe:
            exec:
              command: ["bash", "-c", "pgrep -f roborock_MQTT_bridge.py"]
            initialDelaySeconds: 10
            periodSeconds: 2

          volumeMounts:
            - name: roborock-login
              mountPath: /data
              readOnly: true

      volumes:
        - name: roborock-login
          secret:
            secretName: roborock-login
